[build-system]
# These are required to even start the build process
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "swig>=4.0"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# This ensures we only target Python 3.11 as you requested
build = "cp311-*"

[tool.cibuildwheel.environment]
# Moving the CMake flags here keeps your GitHub Action YAML cleaner
CMAKE_ARGS = "-DCMAKE_POLICY_DEFAULT_CMP0167=NEW"

[tool.cibuildwheel.linux]
# Ensure we use a modern enough manylinux for C++11/14/17 support
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.windows]


[tool.setuptools]
package-dir = {"" = "python"
packages = ["mcnptools"]

[tool.setuptools.package-data]
# This ensures that any generated .so or .pyd files are included in the wheel
"*" = ["*.so", "*.pyd", "*.dll"]
