[project]
name = "mcnptools"
version = "5.3.1" 
description = "MCNP Tools Python Wheels"
requires-python = ">=3.11"
authors = [
    {name = "Name", email = "email"}
]
license = {text = "BSD-3"}  

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "swig>=4.0"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# This ensures Python 3.11
build = "cp311-*"

[tool.cibuildwheel.environment]
CMAKE_ARGS = "-DCMAKE_POLICY_DEFAULT_CMP0167=NEW"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.windows]


[tool.setuptools]
package-dir = {"" = "python"}
packages = ["mcnptools"]

[tool.setuptools.package-data]
"*" = ["*.so", "*.pyd", "*.dll"]
