name: Build and Release Wheels

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build wheels (Linux)
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_BEFORE_ALL_LINUX: >
            dnf install -y epel-release &&
            dnf install -y swig pcre-devel hdf5-devel boost-devel zlib-devel
          
          CIBW_ENVIRONMENT: >
            CMAKE_ARGS="-DBUILD_TESTING=OFF
                        -DPYBIND11_FINDPYTHON=ON
                        -DPython_FIND_STRATEGY=LOCATION
                        -DPython_FIND_IMPLEMENTATIONS=CPython
                        -DPython_FIND_REGISTRY=NEVER"
              
      - name: Install cibuildwheel (Windows)
        if: runner.os == 'Windows'
        run: python -m pip install --upgrade pip && python -m pip install cibuildwheel==3.3.0

      - name: Build wheels (Windows)
        if: runner.os == 'Windows'
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_ENVIRONMENT: >
            CMAKE_ARGS="-DBUILD_TESTING=OFF
                        -DPYBIND11_FINDPYTHON=ON
                        -DPython_FIND_STRATEGY=LOCATION
                        -DPython_FIND_IMPLEMENTATIONS=CPython
                        -DPython_FIND_REGISTRY=NEVER"
        run: python -m cibuildwheel --output-dir wheelhouse --platform windows


      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Create GitHub Release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Only run this job if we pushed a tag
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: cibw-wheels-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          generate_release_notes: true
